### ISSUE TITLE
Add LF info for the signal from IAEA cores on spectrum stats pane 

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#175]
reactors/detector-stats.jsx

line 111 <h6>IAEA Cores</h6>

Add Year-Month range for the load factor data used to calculate the signal.

This would display similar to the way we show the reaction type and cross section info on the Spectrum Stats card

**Comment by stdye** [comment]
Ideally the Spectrum Stats pane would appear something like-

IBD Spectrum Stats: Strumia and Vissani (2003)

or

ES Spectrum Stats: electron antineutrinos

_R__total = xxx NIU

IAEA Cores: 1/19 - 12/19 Load Factor

_R__reac = yyy NIU

**Comment by stdye** [comment]
It looks like this involves aliasing a new variable that codes the date range to export/import to the Spectrum Stats pane.

**Comment by DocOtak** [comment]
This isn't too hard, my first crack at it uses [ISO 8601 Interval Notation](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)

**Comment by stdye** [comment]
Start and End without the clock time looks appropriate to me

**Comment by DocOtak** [comment]
The 100% or 0% is a state of the core objects themselves, technically we store an internal list of "deviations" from the souce data. I think it is relatively easy to access this list (just more stuff to pass in). Things I've thought of for this [UX](https://en.wikipedia.org/wiki/User_experience_design):
* If there is a custom override for one or more cores, display "Custom Load Factor" rather than dates.
* If there is a custom override for one or more cores, display "{dates} with Custom Load Factor".

Or the following combined rules (I don't know how hard it would be to determine the "all" status):
* If there is a custom override for one or more cores, display "{dates} with Custom Load Factor".
* If there is a custom override for all the IAEA cores, display "Custom Load Factor" rather than dates.

**Comment by stdye** [comment]
This is a good suggestion and conveys sufficient information-
 
If there is a custom override for one or more cores, display "Custom Load Factor" rather than dates.
