### ISSUE TITLE
Locations of reactor cores 

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#3]
USERs have no way of knowing the LAT / LON / ELEV values that the web application uses for the reactor cores. This information could be displayed preferably in the Reactor list or less desirably in the 'pop-up' for an individual core (but this assumes that all cores have the same location).

**Comment by DocOtak** [comment]
Added in a6e0b66, perhaps a new issue of "combining" stacked cores on the map into one popup so you can see all the cores there. The problem is that _most_ not _all_ the cores at a single site have the same lat/lon, so we may want to do this with some threshold (.e.g cores within x seconds of each other get one circle+popup)
